### ISSUE TITLE
I can't install version 3.0.0

### ISSUE THREAD

**Issue by Sweeper777** [tbaranes/SwiftyUtils#107]
I am using Swift 4.2 so I guess I should install version 3.0.0, right?

So I did this in Podfile:

    pod 'SwiftyUtils', '3.0.0'

and did `pod update`.

And this error popped up:

```
[!] CocoaPods could not find compatible versions for pod "SwiftyUtils":
  In Podfile:
    SwiftyUtils (= 3.0.0)

None of your spec sources contain a spec satisfying the dependency: `SwiftyUtils (= 3.0.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

If I remove `'3.0.0'`, then version 2.0.0 is installed. What can I do?

**Comment by tbaranes** [comment]
Let me double check if cocoa pods has been correctly released (I'm not using it myself, so...)
Until then, you can target directy the last commit: 

```
pod 'SwiftyUtils', :git => 'https://github.com/tbaranes/SwiftyUtils.git', :commit => '982bffaadf8e831e75d3444dfba56af4d3962224'
```

**Comment by tbaranes** [comment]
I just tried to push 3.0.0 to CocoaPods, but the build is failing. I don't know why right now so I will have to investigate this.

**Comment by Sweeper777** [comment]
I installed the latest commit and it's working. Thanks! I didn't know you could install a specific commit from cocoa pods until now!

**Comment by cddjr** [comment]
pod 'SwiftyUtils', :podspec => 'https://raw.githubusercontent.com/tbaranes/SwiftyUtils/master/SwiftyUtils.podspec'

**Comment by tbaranes** [comment]
Just released 4.0.0 on CocoaPods, this shouldn't be an issue anymore.

**Comment by tbaranes** [comment]
I'm currently trying to release 5.0.0 on CocoaPods doesn't seem to support Swift 5 currently:

```
- NOTE  | xcodebuild:  error: SWIFT_VERSION '5' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'SwiftyUtils')
```

Until that is fixed, I suggest anyone who needs Swift 5 support to target the latest commit.

**Comment by Sweeper777** [comment]
I just updated to Swift 5 and is quite confused by your last comment. Doesn't 4.0.0 support Swift 5 (at least that's what the release notes say...)? I wasn't able to install version 4.0.0 though (same error as above).

 I was able to install other Swift 5 Pods, such as [Eureka 5.0.0](https://github.com/xmartlabs/Eureka/releases/tag/5.0.0) completely fine. Is Swift 5 supported now?

**Comment by tbaranes** [comment]
The v4.0.0 does support Swift 5, but is currently not released on CocoaPods. I will retry to release it on CocoaPods today.

**Comment by tbaranes** [comment]
@Sweeper777 All good! The 4.0.0 is officially released on CocoaPods: https://cocoapods.org/pods/SwiftyUtils

```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SwiftyUtils (4.0.0) successfully published
 📅  August 14th, 08:33
 🌎  https://cocoapods.org/pods/SwiftyUtils
 👍  Tell your friends!
-------------------------------------------------------------------------------- 
```

Sorry for the delay
