### ISSUE TITLE
Won't compile 4.2

### ISSUE THREAD

**Issue by justdan0227** [tbaranes/SwiftyUtils#108]
Just tried to update a project from last summer, and when xCode prompts to convert to 4.2, SwiftyUtils has all kinds of errors.  Am I missing a branch for 4.2?

**Comment by tbaranes** [comment]
4.2 is currently supported by the last release (3.0) in master. I just tried to compile the project and example app, everything seems fine. What kind of errors do you have?

**Comment by justdan0227** [comment]
Sorry just tried it.. This is what I'm seeing.. 
![screen shot 2019-01-10 at 7 43 09 am](https://user-images.githubusercontent.com/918740/50972143-72d47480-14ab-11e9-9161-6492c90ef101.png)
