### ISSUE TITLE
NSTimer fuctions not working

### ISSUE THREAD

**Issue by justdan0227** [tbaranes/SwiftyUtils#13]
Trying to use the NSTimer fuctions XCode 7.3.1 targeted for ios8.  
`var count = 0
NSTimer.every(1.seconds) { timer in
            print("Will print every second")
            if count == 3 {
                timer.invalidate()
            }
            count++
        }`  
says every is Ambiguous ?

**Comment by tbaranes** [comment]
You have to `import SwiftyUtils` in order to use these methods.

**Comment by tbaranes** [comment]
You have to type the closure parameters in order to specify which every are you using:

``` swift
        var count = 0
        NSTimer.every(1.seconds) { (timer: NSTimer) in
            print("Will print every second")
            if count == 3 {
                timer.invalidate()
            }
            count++
        }
```

That's due to a swift limitation since `SwiftyUtils` contains two different `every` with the same signature (there just the closure parameters which change).

**Comment by tbaranes** [comment]
Just fixed the README's example, my bad.

**Comment by justdan0227** [comment]
works!!! thanks!  Great utils!

**Comment by tbaranes** [comment]
Awesome 🎉
