### ISSUE TITLE
 Showing All Messages : package at 'https://github.com/tbaranes/SwiftyUtils.git' @ 832821ab7a0294e1ab5dc5d5329127d8b14badda is using Swift tools version 5.3.0 but the installed version is 5.2.0

### ISSUE THREAD

**Issue by ghost** [tbaranes/SwiftyUtils#151]

**Comment by tbaranes** [comment]
I'm sorry but what's the issue here? It seems you using a conflict with your swift versions

**Comment by ghost** [comment]
Yes This message is Showing

**Comment by ghost** [comment]
Even If I use Branch Master the Also

**Comment by tbaranes** [comment]
Apparently you are using Swift 5.2.0 while it's expecting 5.3.0, you should check which version you are using and maybe change it (or change the expected version)
