### ISSUE TITLE
Readme on Date updated

### ISSUE THREAD

**Issue by justdan0227** [tbaranes/SwiftyUtils#152]
Does the readme need to be corrected for:

Check if a date is in future or past:

let later = Date(timeIntervalSinceNow: -100000)
print(now.isInFuture) // true
print(now.isInPast) // false

later is not used in the example?

**Comment by tbaranes** [comment]
I'm not sure what you mean, these both functions are [available](https://github.com/tbaranes/SwiftyUtils/blob/master/Sources/Extensions/Foundation/Date/DateExtension.swift#L106), what's wrong in the README?

**Comment by Sweeper777** [comment]
I think OP meant that the code comments are wrong (reversed, specifically). `isInFuture` should be false since the date is in the past.

**Comment by tbaranes** [comment]
Aaaah, yes you are right, that's a typo in the README :)

**Comment by tbaranes** [comment]
I fixed it directly on [master](https://github.com/tbaranes/SwiftyUtils/commit/a5b6b85151198f1a9031fe8aef3901ca41051869), thanks for the reporting!
