### ISSUE TITLE
Access String with subscript need Range?

### ISSUE THREAD

**Issue by chenmnkken** [tbaranes/SwiftyUtils#155]
In Readme.md example, access String with subscript do't need Range:

```swift
var string = "hello world"
print(string[0]) // h
print(string[2]) // l
print(string[1...3]) // ell
```

But in Tests/Extensions/Swift/String/StringExtensionTests.swift, access with subscript need use Range, and in my project need use Range too.

```swift
let aString = "Hello world"
aString[Range(1...3)]
```

**Comment by tbaranes** [comment]
You are right, the README is out of date. I just fixed this usage error. Thanks for reporting it!
