### ISSUE TITLE
xCode 8 GM and Swift 3

### ISSUE THREAD

**Issue by justdan0227** [tbaranes/SwiftyUtils#26]
Attempting to use the pod and getting:

Module file's minimum deployment target is ios10.0 v10.0 ??? All set to ios10 (really want it to be ios9)

**Comment by tbaranes** [comment]
That's weird, it should be 8.0. Just give a quick look at the podspec, everything seems good. I will give it a a deeper look next week. 

Also, can you try to target the master directly (just to see if you have the same error)? 

```
pod 'SwiftyUtils', :git => https://github.com/tbaranes/SwiftyUtils.git
```

**Comment by justdan0227** [comment]
yeah something is off.. If i create a clean new project it works just fine.   Investigating...

**Comment by justdan0227** [comment]
Ok so if I have it all set to iOS10 it works just fine.  However if I want to target ios9 as well and set Deployment to ios9, it fails?

**Comment by tbaranes** [comment]
That's really weird (still didn't try myself). What version of CocoaPods are you using?

**Comment by justdan0227** [comment]
my bad. sorry .. if I set it to 8 it fails.  9 is just fine.  pod version is 0.39.0

**Comment by tbaranes** [comment]
So, is it ok for you or is there still an issue? 😆

**Comment by justdan0227** [comment]
Yeah with using pod version < 1.0 I had to also add 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
```

to get past the version issue that pod has.  Thanks.  This can be closed

**Comment by tbaranes** [comment]
I see, I think if you use their last beta version, it should work as expected. A lot of things has been broken with the new toolchain / Swift 3.

Anyway, glad to see that's working for you! :)

**Comment by justdan0227** [comment]
Yeah thanks.. unfortunately I can't use that latest and greatest pd because I have a legacy Ruby On Rails project that will not work with pod > 1.0.. uggg :)
