### ISSUE TITLE
Can you rename the methods so that they follow the Swift 3 API design guidelines?

### ISSUE THREAD

**Issue by Sweeper777** [tbaranes/SwiftyUtils#33]
For example, the `shuffle()` method on immutable collections should be renamed to `shuffled()`. All the Reusable Formatters should be `shared` instead of `sharedInstance`. `String.isNumber()` should be a computed property instead of a method.

**Comment by tbaranes** [comment]
I fully agree with you!  The migration to Swift 3 is a real pain since there's so much things to change 😬
