### ISSUE TITLE
Do you think an appDelegate() function is needed?

### ISSUE THREAD

**Issue by Sweeper777** [tbaranes/SwiftyUtils#93]
I often needed to access the `appDelegate` for various reasons, for accessing the `window` property, or the core data context. Currently, I'm using this:

```
(UIApplication.shared.delegate as! AppDelegate).window
```

I feel like this is kind of a lot of work. I usually start typing `UIApplication.shared...` then realise I need brackets and I'm not really a fan of them.

Do you think adding such a method would be good?

```
extension UIApplication {
    static func delegate<T: UIApplicationDelegate>(_ type: T.Type) -> T? {
        return UIApplication.shared.delegate as? T
    }
}
```

**Comment by tbaranes** [comment]
Completely agree, I have the same issue. Let's go for it 👍
