### ISSUE TITLE
Swift 4 migration

### ISSUE THREAD

**Issue by tbaranes** [tbaranes/SwiftyUtils#95]
Removing deprecated methods...

**Comment by tbaranes** [comment]
Starting with #96, the project itself will be supporting Swift 4 and Xcode 9. Work left: removing the useless / out of date methods starting with Swift 4. Any PRs welcome!

**Comment by vadimvitvickiy** [comment]
Still can't build with xcode 9 and swift 4?

**Comment by tbaranes** [comment]
It's working and building as expected, did you get an an issue?

**Comment by vadimvitvickiy** [comment]
Yes, few errors, I have to fix them to build

**Comment by tbaranes** [comment]
Can you try to target master directly and let me know if you still have them?

**Comment by tbaranes** [comment]
@pluckq Just released 2.0 with official Swift 4 support, it should fixed all the issues you had.
